name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install Native-Code-Compiler
      run: dotnet add package Microsoft.DotNet.ILCompiler --prerelease
    - name: Build Native Library
      run: dotnet publish /p:NativeLib=Shared /p:SelfContained=true -r linux-x64
